import * as fs from 'fs';
// import * as csv from 'csv-parser';

/**
 * @NOTE
 * Always remove the bitmap field from the objects bit_to_field and field_to_bit
 * as the bitmap is cached in memory and not sent by the user
 *
 * The bit_to_field and field_to_bit constants are generated by running the
 * 2 functions below : get_bit_to_filed_json() and get_name_to_bit_json()
 */

//all values separated
export const bit_to_field = {
  // '1': {
  //   name: 'Bitmap Indicator',
  //   format: '',
  //   representation: 'b 64',
  //   bit: '1',
  // },
  '2': {
    name: 'Primary account number (PAN)',
    format: 'LLVAR',
    representation: 'n ..19',
    bit: '2',
  },
  '3': {
    name: 'Processing code',
    format: '',
    representation: 'n 6',
    bit: '3',
  },
  '4': {
    name: 'Amount transaction',
    format: '',
    representation: 'n 12',
    bit: '4',
  },
  '5': {
    name: 'Amount settlement',
    format: '',
    representation: 'n 12',
    bit: '5',
  },
  '6': {
    name: 'Amount cardholder billing',
    format: '',
    representation: 'n 12',
    bit: '6',
  },
  '7': {
    name: 'Date and time transmission',
    format: 'MMDDhhmmss',
    representation: 'n 10',
    bit: '7',
  },
  '8': {
    name: 'Amount cardholder billing fee',
    format: '',
    representation: 'n 8',
    bit: '8',
  },
  '9': {
    name: 'Conversion rate settlement',
    format: '',
    representation: 'n 8',
    bit: '9',
  },
  '10': {
    name: 'Conversion rate cardholder billing',
    format: '',
    representation: 'n 8',
    bit: '10',
  },
  '11': {
    name: 'Systems trace audit number',
    format: '',
    representation: 'n 6',
    bit: '11',
  },
  '12': {
    name: 'Time local transaction',
    format: 'hhmmss',
    representation: 'n 6',
    bit: '12',
  },
  '13': {
    name: 'Date local transaction',
    format: 'MMDD',
    representation: 'n 4',
    bit: '13',
  },
  '14': {
    name: 'Date expiration',
    format: 'YYMM',
    representation: 'n 4',
    bit: '14',
  },
  '15': {
    name: 'Date settlement',
    format: 'MMDD',
    representation: 'n 4',
    bit: '15',
  },
  '16': {
    name: 'Date conversion',
    format: 'MMDD',
    representation: 'n 4',
    bit: '16',
  },
  '17': {
    name: 'Date capture',
    format: 'MMDD',
    representation: 'n 4',
    bit: '17',
  },
  '18': {
    name: 'Merchant type',
    format: '',
    representation: 'n 4',
    bit: '18',
  },
  '19': {
    name: 'Acquiring institution country code',
    format: '',
    representation: 'n 3',
    bit: '19',
  },
  '20': {
    name: 'Primary account number (PAN) extended country code',
    format: '',
    representation: 'n 3',
    bit: '20',
  },
  '21': {
    name: 'Forwarding institution country code',
    format: '',
    representation: 'n 3',
    bit: '21',
  },
  '22': {
    name: 'Point of service entry mode',
    format: '',
    representation: 'n 3',
    bit: '22',
  },
  '23': {
    name: 'Card sequence number',
    format: '',
    representation: 'n 3',
    bit: '23',
  },
  '24': {
    name: 'Function code',
    format: '',
    representation: 'n 3',
    bit: '24',
  },
  '25': {
    name: 'Point of service condition code',
    format: '',
    representation: 'n 2',
    bit: '25',
  },
  '26': {
    name: 'Point of service capture code',
    format: '',
    representation: 'n 2',
    bit: '26',
  },
  '27': {
    name: 'Authorisation identification response length',
    format: '',
    representation: 'n 1',
    bit: '27',
  },
  '28': {
    name: 'Amount transaction fee',
    format: '',
    representation: 'n 8',
    bit: '28',
  },
  '29': {
    name: 'Amount settlement fee',
    format: '',
    representation: 'n 8',
    bit: '29',
  },
  '30': {
    name: 'Amount transaction processing fee',
    format: '',
    representation: 'n 8',
    bit: '30',
  },
  '31': {
    name: 'Amount settlement processing fee',
    format: '',
    representation: 'n 8',
    bit: '31',
  },
  //might require change in representation
  '32': {
    name: 'Acquiring institution identification code',
    format: 'LLVAR',
    representation: 'n ..11',
    bit: '32',
  },
  '33': {
    name: 'Forwarding institution identification code',
    format: 'LLVAR',
    representation: 'n ..11',
    bit: '33',
  },
  '34': {
    name: 'Primary account number extended',
    format: 'LLVAR',
    representation: 'n ..28',
    bit: '34',
  },
  '35': {
    name: 'Track 2 data',
    format: 'LLVAR',
    representation: 'z ..37',
    bit: '35',
  },
  '36': {
    name: 'Track 3 data',
    format: 'LLLVAR',
    representation: 'z ..104',
    bit: '36',
  },
  '37': {
    name: 'Retrieval reference number',
    format: '',
    representation: 'an 12',
    bit: '37',
  },
  '38': {
    name: 'Authorization identification response',
    format: '',
    representation: 'an 6',
    bit: '38',
  },
  '39': {
    name: 'Response code',
    format: '',
    representation: 'an 2',
    bit: '39',
  },
  '40': {
    name: 'Service restriction code',
    format: '',
    representation: 'an 3',
    bit: '40',
  },
  '41': {
    name: 'Card acceptor terminal identification',
    format: '',
    representation: 'ans 8',
    bit: '41',
  },
  '42': {
    name: 'Card acceptor identification code',
    format: '',
    representation: 'ans 15',
    bit: '42',
  },
  '43': {
    name: 'Card acceptor name/location',
    format: '',
    representation: 'ans 40',
    bit: '43',
  },
  '44': {
    name: 'Additional response data',
    format: 'LLVAR',
    representation: 'an ..25',
    bit: '44',
  },
  '45': {
    name: 'Track 1 data',
    format: 'LLVAR',
    representation: 'an ..76',
    bit: '45',
  },
  '46': {
    name: 'Additional data ISO',
    format: 'LLLVAR',
    representation: 'an ..999',
    bit: '46',
  },
  '47': {
    name: 'Additional data national',
    format: 'LLLVAR',
    representation: 'an ..999',
    bit: '47',
  },
  '48': {
    name: 'Additional data private',
    format: 'LLLVAR',
    representation: 'an ..999',
    bit: '48',
  },
  '49': {
    name: 'Currency code transaction',
    format: '',
    representation: 'an 3',
    bit: '49',
  },
  '50': {
    name: 'Currency code settlement',
    format: '',
    representation: 'an 3',
    bit: '50',
  },
  '51': {
    name: 'Currency code card holder billing',
    format: '',
    representation: 'a 3',
    bit: '51',
  },
  '52': {
    name: 'Personal identification number (PIN) data',
    format: '',
    representation: 'b 16',
    bit: '52',
  },
  '53': {
    name: 'Security related control information',
    format: '',
    representation: 'n 18',
    bit: '53',
  },
  '54': {
    name: 'Additional amounts',
    format: 'LLLVAR',
    representation: 'an ..120',
    bit: '54',
  },
  '55': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '55',
  },
  '56': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 56,
  },
  '57': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '57',
  },
  '58': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 58,
  },
  '59': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 59,
  },
  '60': {
    name: 'Reserved for private use-60',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '60',
  },
  '61': {
    name: 'Reserved for private use-61',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 61,
  },
  '62': {
    name: 'Reserved for private use-62',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 62,
  },
  '63': {
    name: 'Reserved for private use-63',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 63,
  },
  '64': {
    name: 'Message authentication code (MAC) field',
    format: '',
    representation: 'b 16',
    bit: '64',
  },
  '65': {
    name: 'Reserved for ISO use',
    format: '',
    representation: '',
    bit: '65',
  },
  '66': {
    name: 'Settlement code',
    format: '',
    representation: 'n 1',
    bit: '66',
  },
  '67': {
    name: 'Extended payment code',
    format: '',
    representation: 'n 2',
    bit: '67',
  },
  '68': {
    name: 'Receiving institution country code',
    format: '',
    representation: 'n 3',
    bit: '68',
  },
  '69': {
    name: 'Settlement institution country code',
    format: '',
    representation: 'n 3',
    bit: '69',
  },
  '70': {
    name: 'Network management information code',
    format: '',
    representation: 'n 3',
    bit: '70',
  },
  '71': {
    name: 'Message number',
    format: '',
    representation: 'n 4',
    bit: '71',
  },
  '72': {
    name: 'Data record',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '72',
  },
  '73': {
    name: 'Date action',
    format: 'YYMMDD',
    representation: 'n 6',
    bit: '73',
  },
  '74': {
    name: 'Credits number',
    format: '',
    representation: 'n 10',
    bit: '74',
  },
  '75': {
    name: 'Credits reversal number',
    format: '',
    representation: 'n 10',
    bit: '75',
  },
  '76': {
    name: 'Debits number',
    format: '',
    representation: 'n 10',
    bit: '76',
  },
  '77': {
    name: 'Debits reversal number',
    format: '',
    representation: 'n 10',
    bit: '77',
  },
  '78': {
    name: 'Transfer number',
    format: '',
    representation: 'n 10',
    bit: '78',
  },
  '79': {
    name: 'Transfer reversal number',
    format: '',
    representation: 'n 10',
    bit: '79',
  },
  '80': {
    name: 'Inquiries number',
    format: '',
    representation: 'n 10',
    bit: '80',
  },
  '81': {
    name: 'Authorisations number',
    format: '',
    representation: 'n 10',
    bit: '81',
  },
  '82': {
    name: 'Credits processing fee amount',
    format: '',
    representation: 'n 12',
    bit: '82',
  },
  '83': {
    name: 'Credits transaction fee amount',
    format: '',
    representation: 'n 12',
    bit: '83',
  },
  '84': {
    name: 'Debits processing fee amount',
    format: '',
    representation: 'n 12',
    bit: '84',
  },
  '85': {
    name: 'Debits transaction fee amount',
    format: '',
    representation: 'n 12',
    bit: '85',
  },
  '86': {
    name: 'Credits amount',
    format: '',
    representation: 'n 15',
    bit: '86',
  },
  '87': {
    name: 'Credits reversal amount',
    format: '',
    representation: 'n 15',
    bit: '87',
  },
  '88': {
    name: 'Debits amount',
    format: '',
    representation: 'n 15',
    bit: '88',
  },
  '89': {
    name: 'Debits reversal amount',
    format: '',
    representation: 'n 15',
    bit: '89',
  },
  '90': {
    name: 'Original data elements',
    format: '',
    representation: 'n 42',
    bit: '90',
  },
  '91': {
    name: 'File update code',
    format: '',
    representation: 'an 1',
    bit: '91',
  },
  '92': {
    name: 'File security code',
    format: '',
    representation: 'n 2',
    bit: '92',
  },
  '93': {
    name: 'Response indicator',
    format: '',
    representation: 'n 5',
    bit: '93',
  },
  '94': {
    name: 'Service indicator',
    format: '',
    representation: 'an 7',
    bit: '94',
  },
  '95': {
    name: 'Replacement amounts',
    format: '',
    representation: 'an 42',
    bit: '95',
  },
  '96': {
    name: 'Message security code',
    format: '',
    representation: 'an 8',
    bit: '96',
  },
  '97': {
    name: 'Amount net settlement',
    format: '',
    representation: 'n 16',
    bit: '97',
  },
  '98': { name: 'Payee', format: '', representation: 'ans 25', bit: '98' },
  '99': {
    name: 'Settlement institution identification code',
    format: 'LLVAR',
    representation: 'n ..11',
    bit: '99',
  },
  '100': {
    name: 'Receiving institution identification code',
    format: 'LLVAR',
    representation: 'n ..11',
    bit: '100',
  },
  '101': {
    name: 'File name',
    format: 'LLVAR',
    representation: 'ans ..99',
    bit: '101',
  },
  '102': {
    name: 'Account identification 1',
    format: 'LLVAR',
    representation: 'ans ..28',
    bit: '102',
  },
  '103': {
    name: 'Account identification 2',
    format: 'LLVAR',
    representation: 'ans ..28',
    bit: '103',
  },
  '104': {
    name: 'Transaction description',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '104',
  },
  '105': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '105',
  },
  '106': {
    name: 'Reserved for ISO use',
    format: 'LLVAR',
    representation: 'ans ..999',
    bit: 106,
  },
  '107': {
    name: 'Reserved for ISO use',
    format: 'LLVAR',
    representation: 'ans ..999',
    bit: 107,
  },
  '108': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 108,
  },
  '109': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 109,
  },
  '110': {
    name: 'Reserved for ISO use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 110,
  },
  '111': {
    name: 'Reserved for ISO use',
    format: 'LLVAR',
    representation: 'ans ..999',
    bit: 111,
  },
  '112': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '112',
  },
  '113': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 113,
  },
  '114': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 114,
  },
  '115': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 115,
  },
  '116': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 116,
  },
  '117': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 117,
  },
  '118': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 118,
  },
  '119': {
    name: 'Reserved for national use',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 119,
  },
  '120': {
    name: 'Reserved for private use-120',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: '120',
  },
  '121': {
    name: 'Reserved for private use-121',
    format: 'LLVAR',
    representation: 'ans ..999',
    bit: 121,
  },
  '122': {
    name: 'Reserved for private use-122',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 122,
  },
  '123': {
    name: 'Reserved for private use-123',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 123,
  },
  '124': {
    name: 'Reserved for private use-124',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 124,
  },
  '125': {
    name: 'Reserved for private use-125',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 125,
  },
  '126': {
    name: 'Reserved for private use-126',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 126,
  },
  '127': {
    name: 'Reserved for private use-127',
    format: 'LLLVAR',
    representation: 'ans ..999',
    bit: 127,
  },
  '128': {
    name: 'Message authentication code (MAC) field',
    format: '',
    representation: 'b 64',
    bit: '128',
  },
};

export const field_to_bit = {
  // 'Bitmap Indicator': {
  //   bit: '1',
  //   format: '',
  //   representation: 'b 64',
  //   name: 'Bitmap Indicator',
  // },
  'Primary account number (PAN)': {
    bit: '2',
    format: 'LLVAR',
    representation: 'n ..19',
    name: 'Primary account number (PAN)',
  },
  'Processing code': {
    bit: '3',
    format: '',
    representation: 'n 6',
    name: 'Processing code',
  },
  'Amount transaction': {
    bit: '4',
    format: '',
    representation: 'n 12',
    name: 'Amount transaction',
  },
  'Amount settlement': {
    bit: '5',
    format: '',
    representation: 'n 12',
    name: 'Amount settlement',
  },
  'Amount cardholder billing': {
    bit: '6',
    format: '',
    representation: 'n 12',
    name: 'Amount cardholder billing',
  },
  'Date and time transmission': {
    bit: '7',
    format: 'MMDDhhmmss',
    representation: 'n 10',
    name: 'Date and time transmission',
  },
  'Amount cardholder billing fee': {
    bit: '8',
    format: '',
    representation: 'n 8',
    name: 'Amount cardholder billing fee',
  },
  'Conversion rate settlement': {
    bit: '9',
    format: '',
    representation: 'n 8',
    name: 'Conversion rate settlement',
  },
  'Conversion rate cardholder billing': {
    bit: '10',
    format: '',
    representation: 'n 8',
    name: 'Conversion rate cardholder billing',
  },
  'Systems trace audit number': {
    bit: '11',
    format: '',
    representation: 'n 6',
    name: 'Systems trace audit number',
  },
  'Time local transaction': {
    bit: '12',
    format: 'hhmmss',
    representation: 'n 6',
    name: 'Time local transaction',
  },
  'Date local transaction': {
    bit: '13',
    format: 'MMDD',
    representation: 'n 4',
    name: 'Date local transaction',
  },
  'Date expiration': {
    bit: '14',
    format: 'YYMM',
    representation: 'n 4',
    name: 'Date expiration',
  },
  'Date settlement': {
    bit: '15',
    format: 'MMDD',
    representation: 'n 4',
    name: 'Date settlement',
  },
  'Date conversion': {
    bit: '16',
    format: 'MMDD',
    representation: 'n 4',
    name: 'Date conversion',
  },
  'Date capture': {
    bit: '17',
    format: 'MMDD',
    representation: 'n 4',
    name: 'Date capture',
  },
  'Merchant type': {
    bit: '18',
    format: '',
    representation: 'n 4',
    name: 'Merchant type',
  },
  'Acquiring institution country code': {
    bit: '19',
    format: '',
    representation: 'n 3',
    name: 'Acquiring institution country code',
  },
  'Primary account number (PAN) extended country code': {
    bit: '20',
    format: '',
    representation: 'n 3',
    name: 'Primary account number (PAN) extended country code',
  },
  'Forwarding institution country code': {
    bit: '21',
    format: '',
    representation: 'n 3',
    name: 'Forwarding institution country code',
  },
  'Point of service entry mode': {
    bit: '22',
    format: '',
    representation: 'n 3',
    name: 'Point of service entry mode',
  },
  'Card sequence number': {
    bit: '23',
    format: '',
    representation: 'n 3',
    name: 'Card sequence number',
  },
  'Function code': {
    bit: '24',
    format: '',
    representation: 'n 3',
    name: 'Function code',
  },
  'Point of service condition code': {
    bit: '25',
    format: '',
    representation: 'n 2',
    name: 'Point of service condition code',
  },
  'Point of service capture code': {
    bit: '26',
    format: '',
    representation: 'n 2',
    name: 'Point of service capture code',
  },
  'Authorisation identification response length': {
    bit: '27',
    format: '',
    representation: 'n 1',
    name: 'Authorisation identification response length',
  },
  'Amount transaction fee': {
    bit: '28',
    format: '',
    representation: 'n 8',
    name: 'Amount transaction fee',
  },
  'Amount settlement fee': {
    bit: '29',
    format: '',
    representation: 'n 8',
    name: 'Amount settlement fee',
  },
  'Amount transaction processing fee': {
    bit: '30',
    format: '',
    representation: 'n 8',
    name: 'Amount transaction processing fee',
  },
  'Amount settlement processing fee': {
    bit: '31',
    format: '',
    representation: 'n 8',
    name: 'Amount settlement processing fee',
  },
  'Acquiring institution identification code': {
    bit: '32',
    format: 'LLVAR',
    representation: 'n ..11',
    name: 'Acquiring institution identification code',
  },
  'Forwarding institution identification code': {
    bit: '33',
    format: 'LLVAR',
    representation: 'n ..11',
    name: 'Forwarding institution identification code',
  },
  'Primary account number extended': {
    bit: '34',
    format: 'LLVAR',
    representation: 'n ..28',
    name: 'Primary account number extended',
  },
  'Track 2 data': {
    bit: '35',
    format: 'LLVAR',
    representation: 'z ..37',
    name: 'Track 2 data',
  },
  'Track 3 data': {
    bit: '36',
    format: 'LLLVAR',
    representation: 'z ..104',
    name: 'Track 3 data',
  },
  'Retrieval reference number': {
    bit: '37',
    format: '',
    representation: 'an 12',
    name: 'Retrieval reference number',
  },
  'Authorization identification response': {
    bit: '38',
    format: '',
    representation: 'an 6',
    name: 'Authorization identification response',
  },
  'Response code': {
    bit: '39',
    format: '',
    representation: 'an 2',
    name: 'Response code',
  },
  'Service restriction code': {
    bit: '40',
    format: '',
    representation: 'an 3',
    name: 'Service restriction code',
  },
  'Card acceptor terminal identification': {
    bit: '41',
    format: '',
    representation: 'ans 8', //changed from ans 16 to ans 8
    name: 'Card acceptor terminal identification',
  },
  'Card acceptor identification code': {
    bit: '42',
    format: '',
    representation: 'ans 15',
    name: 'Card acceptor identification code',
  },
  'Card acceptor name/location': {
    bit: '43',
    format: '',
    representation: 'ans 40',
    name: 'Card acceptor name/location',
  },
  'Additional response data': {
    bit: '44',
    format: 'LLVAR',
    representation: 'an ..25',
    name: 'Additional response data',
  },
  'Track 1 data': {
    bit: '45',
    format: 'LLVAR',
    representation: 'an ..76',
    name: 'Track 1 data',
  },
  'Additional data ISO': {
    bit: '46',
    format: 'LLLVAR',
    representation: 'an ..999',
    name: 'Additional data ISO',
  },
  'Additional data national': {
    bit: '47',
    format: 'LLLVAR',
    representation: 'an ..999',
    name: 'Additional data national',
  },
  'Additional data private': {
    bit: '48',
    format: 'LLLVAR',
    representation: 'an ..999',
    name: 'Additional data private',
  },
  'Currency code transaction': {
    bit: '49',
    format: '',
    representation: 'an 3',
    name: 'Currency code transaction',
  },
  'Currency code settlement': {
    bit: '50',
    format: '',
    representation: 'an 3',
    name: 'Currency code settlement',
  },
  'Currency code card holder billing': {
    bit: '51',
    format: '',
    representation: 'a 3',
    name: 'Currency code card holder billing',
  },
  'Personal identification number (PIN) data': {
    bit: '52',
    format: '',
    representation: 'b 16',
    name: 'Personal identification number (PIN) data',
  },
  'Security related control information': {
    bit: '53',
    format: '',
    representation: 'n 18',
    name: 'Security related control information',
  },
  'Additional amounts': {
    bit: '54',
    format: 'LLLVAR',
    representation: 'an ..120',
    name: 'Additional amounts',
  },
  'Reserved for ISO use': {
    bit: '105-111',
    format: '',
    representation: '',
    name: 'Reserved for ISO use',
  },
  'Reserved for national use': {
    bit: '112-119',
    format: 'LLVAR',
    representation: 'ans ..999',
    name: 'Reserved for national use',
  },
  'Reserved for private use': {
    bit: '120-127',
    format: '',
    representation: '',
    name: 'Reserved for private use',
  },
  'Message authentication code (MAC) field': {
    bit: '128',
    format: '',
    representation: 'b 16',
    name: 'Message authentication code (MAC) field',
  },
  'Settlement code': {
    bit: '66',
    format: '',
    representation: 'n 1',
    name: 'Settlement code',
  },
  'Extended payment code': {
    bit: '67',
    format: '',
    representation: 'n 2',
    name: 'Extended payment code',
  },
  'Receiving institution country code': {
    bit: '68',
    format: '',
    representation: 'n 3',
    name: 'Receiving institution country code',
  },
  'Settlement institution country code': {
    bit: '69',
    format: '',
    representation: 'n 3',
    name: 'Settlement institution country code',
  },
  'Network management information code': {
    bit: '70',
    format: '',
    representation: 'n 3',
    name: 'Network management information code',
  },
  'Message number': {
    bit: '71',
    format: '',
    representation: 'n 4',
    name: 'Message number',
  },
  'Data record': {
    bit: '72',
    format: 'LLLVAR',
    representation: 'ans ..999',
    name: 'Data record',
  },
  'Date action': {
    bit: '73',
    format: 'YYMMDD',
    representation: 'n 6',
    name: 'Date action',
  },
  'Credits number': {
    bit: '74',
    format: '',
    representation: 'n 10',
    name: 'Credits number',
  },
  'Credits reversal number': {
    bit: '75',
    format: '',
    representation: 'n 10',
    name: 'Credits reversal number',
  },
  'Debits number': {
    bit: '76',
    format: '',
    representation: 'n 10',
    name: 'Debits number',
  },
  'Debits reversal number': {
    bit: '77',
    format: '',
    representation: 'n 10',
    name: 'Debits reversal number',
  },
  'Transfer number': {
    bit: '78',
    format: '',
    representation: 'n 10',
    name: 'Transfer number',
  },
  'Transfer reversal number': {
    bit: '79',
    format: '',
    representation: 'n 10',
    name: 'Transfer reversal number',
  },
  'Inquiries number': {
    bit: '80',
    format: '',
    representation: 'n 10',
    name: 'Inquiries number',
  },
  'Authorisations number': {
    bit: '81',
    format: '',
    representation: 'n 10',
    name: 'Authorisations number',
  },
  'Credits processing fee amount': {
    bit: '82',
    format: '',
    representation: 'n 12',
    name: 'Credits processing fee amount',
  },
  'Credits transaction fee amount': {
    bit: '83',
    format: '',
    representation: 'n 12',
    name: 'Credits transaction fee amount',
  },
  'Debits processing fee amount': {
    bit: '84',
    format: '',
    representation: 'n 12',
    name: 'Debits processing fee amount',
  },
  'Debits transaction fee amount': {
    bit: '85',
    format: '',
    representation: 'n 12',
    name: 'Debits transaction fee amount',
  },
  'Credits amount': {
    bit: '86',
    format: '',
    representation: 'n 15',
    name: 'Credits amount',
  },
  'Credits reversal amount': {
    bit: '87',
    format: '',
    representation: 'n 15',
    name: 'Credits reversal amount',
  },
  'Debits amount': {
    bit: '88',
    format: '',
    representation: 'n 15',
    name: 'Debits amount',
  },
  'Debits reversal amount': {
    bit: '89',
    format: '',
    representation: 'n 15',
    name: 'Debits reversal amount',
  },
  'Original data elements': {
    bit: '90',
    format: '',
    representation: 'n 42',
    name: 'Original data elements',
  },
  'File update code': {
    bit: '91',
    format: '',
    representation: 'an 1',
    name: 'File update code',
  },
  'File security code': {
    bit: '92',
    format: '',
    representation: 'n 2',
    name: 'File security code',
  },
  'Response indicator': {
    bit: '93',
    format: '',
    representation: 'n 5',
    name: 'Response indicator',
  },
  'Service indicator': {
    bit: '94',
    format: '',
    representation: 'an 7',
    name: 'Service indicator',
  },
  'Replacement amounts': {
    bit: '95',
    format: '',
    representation: 'an 42',
    name: 'Replacement amounts',
  },
  'Message security code': {
    bit: '96',
    format: '',
    representation: 'an 8',
    name: 'Message security code',
  },
  'Amount net settlement': {
    bit: '97',
    format: '',
    representation: 'n 16',
    name: 'Amount net settlement',
  },
  Payee: { bit: '98', format: '', representation: 'ans 25', name: 'Payee' },
  'Settlement institution identification code': {
    bit: '99',
    format: 'LLVAR',
    representation: 'n ..11',
    name: 'Settlement institution identification code',
  },
  'Receiving institution identification code': {
    bit: '100',
    format: 'LLVAR',
    representation: 'n ..11',
    name: 'Receiving institution identification code',
  },
  'File name': {
    bit: '101',
    format: 'LLVAR',
    representation: 'ans ..99',
    name: 'File name',
  },
  'Account identification 1': {
    bit: '102',
    format: 'LLVAR',
    representation: 'ans ..28',
    name: 'Account identification 1',
  },
  'Account identification 2': {
    bit: '103',
    format: 'LLVAR',
    representation: 'ans ..28',
    name: 'Account identification 2',
  },
  'Transaction description': {
    bit: '104',
    format: 'LLLVAR',
    representation: 'ans ..999',
    name: 'Transaction description',
  },
};

const ISO_FILE_PATH = 'src/data/iso_data.csv';

export const get_bit_to_field_json = () => {
  const results = {};

  // fs.createReadStream(ISO_FILE_PATH)
  //   .pipe(csv())
  //   .on('data', (data) => {
  //     console.log('data ', data);

  //     //if entry is like 120-127, then loop through all the values
  //     //and add entries for all the values
  //     if (isNaN(data['bit'])) {
  //       const splittedValue = data['bit'].split('-');
  //       console.log({ splittedValue });
  //       const start = splittedValue[0];
  //       const end = splittedValue[1];
  //       for (let i = start; i <= end; ++i) {
  //         results[i] = {
  //           name: data['name'],
  //           format: 'LLVAR', //temporary for testing purposes
  //           representation: data['representation'],
  //           bit: i,
  //         };
  //       }
  //     } else {
  //       results[data['bit']] = {
  //         name: data['name'],
  //         format: data['format'],
  //         representation: data['representation'],
  //         bit: data['bit'],
  //       };
  //     }
  //   })
  //   .on('end', () => {
  //     console.log(
  //       '---------- Here is what each bit in ISO-8583 indicates ----------',
  //     );
  //     console.log(results);
  //   });

  return results;
};

export const get_name_to_bit_json = () => {
  // const results = {};
  // fs.createReadStream(ISO_FILE_PATH)
  //   .pipe(csv())
  //   .on('data', (data) => {
  //     results[data['name']] = {
  //       bit: data['bit'],
  //       format: data['format'],
  //       representation: data['representation'],
  //       name: data['name'],
  //     };
  //   })
  //   .on('end', () => {
  //     console.log(
  //       '---------- Here is what each bit in ISO-8583 indicates ----------',
  //     );
  //     console.log(results);
  //   });
  // return results;
};
